version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: mucha
      POSTGRES_PASSWORD: mucha
      POSTGRES_DB: nest
    networks:
      - nest
networks:
  nest:
    driver: bridge
